name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  build-java-quarkus:
    name: Build in Java Quarkus
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build Java Quarkus
        run: mvn clean package

  deploy:
    needs:
      - build-java-quarkus
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - name: Executing remote ssh commands using ssh key
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY}}
          command: |
            cd /home/ubuntu/java-quarkus-senac/
            sudo docker stop java-container-quarkus
            sudo docker rm java-container-quarkus
            sudo docker build  -t java-img-quarkus .
            sudo docker run -d --name java-container-quarkus -p 7000:7000 java-img-quarkus:latest
            